### ISSUE TITLE
exoflex: Switch

### ISSUE THREAD

**Issue by gabriellaputri** [kodefox/infra#528]
**Describe the bug**
`width` props doesn't actually widen the track, more like scaling it.
![Kapture 2020-07-02 at 13 18 00](https://user-images.githubusercontent.com/54926653/86323243-b1915800-bc66-11ea-8dde-0c1ad562de14.gif)

when setting the width manually from `trackStyle` props, it produce a bug where the thumb doesn't reach the end.
<img width="400" alt="Screen Shot 2020-07-02 at 12 18 24 PM" src="https://user-images.githubusercontent.com/54926653/86323284-c4a42800-bc66-11ea-9999-45797eaf03dc.png">

**To Reproduce**
1. Set `width` to any value, ex. `width={60}`
2. Set width from `trackStyle`, ex. `trackStyle={{ width: 80 }}`

**Expected behavior**
- `width` props should only lengthen the track (or maybe you can change the props name to `size`)
- setting `width` in `trackStyle` should work properly

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS12.4
 - Package version: 3.4.0

**Comment by oshimayoan** [comment]
Indeed, `size` is a better name for that but we can't do that for now as it will be a breaking change. We want to avoid any breaking changes for any fixes at all costs, except when we planning to release a new major version.

And thanks for finding this bug, we'll make a PR for this fix soon.
